version: "3.8"

services:
  frontend:
    depends_on:
      - backend
    build: ./client
    ports:
      - 3000:3000

  backend:
    depends_on:
      - db
    build: ./server
    ports:
      - 3001:3001
    environment:
      DB_URL: mongodb://db/telecrit
    command: ["sh", "docker-entrypoint.sh"]

  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - telecrit:/data/db

volumes:
  telecrit:
